### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by facultymatt** [chaoran/node-throttle#1]
Redis connections that require auth fail. I've tried passing a connection string like so: 

```
{ 
    port: 17789,
    options: {
        auth_pass: 'password' 
    },
    host: 'host.hosting.com' 
}
```

According to the node redis documentation, this should try to auto connect. 

Any ideas?

**Comment by facultymatt** [comment]
For the record, I was able to get around this by using 

```
if(connection.options.auth_pass) {
    pass = connection.options.auth_pass;
    delete connection.options.auth_pass;
}

// create our Throttle
Throttle.configure(connection);

// if we have a password, authorize
if(pass) {
    Throttle.rdb.auth(pass, function() {
        console.info('REDIS Server connected');
    });    
}
```

@note that we can access `Throttle.rdb` which is the redis object, so we can do auth on our own.

**Comment by chaoran** [comment]
@facultymatt You don't need to wrap options in the options field. You should pass a connection string like this:

```
{ 
    port: 17789,
    auth_pass: 'password',
    host: 'host.hosting.com' 
}
```
